ab_core_accueil:
    path:     /{_locale}
    defaults: { _controller: ABCoreBundle:Core:index, _locale: fr }
    requirements:
        _locale: fr|en

ab_core_reservation:
    path:    /reservation/{_locale}
    defaults: { _controller: ABCoreBundle:Core:reservation }
    requirements:
        _locale: fr|en

ab_core_updateresa:
    path: /modification_reservation/{id}/{_locale}
    defaults: {_controller: ABCoreBundle:Core:updateresa}
    requirements:
        id: \d+
        _locale: fr|en

ab_core_visiteur:
    path:    /visiteur/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Core:visiteur }
    requirements:
        id: \d+
        _locale: fr|en

ab_core_paiement:
    path:    /paiement/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Core:paiement }
    requirements:
        id: \d+
        _locale: fr|en

ab_core_partage:
    path:    /partage/{_locale}
    defaults: { _controller: ABCoreBundle:Core:partage }
    requirements:
         _locale: fr|en

ab_core_error:
    path:    /error/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Core:error }
    requirements:
         id: \d+
         _locale: fr|en



