ab_core_accueil:
    path:     /{_locale}
    defaults: { _controller: ABCoreBundle:Core:index, _locale: fr }
    requirements:
        _locale: fr|en

ab_core_reservation:
    path:    /reservation/{_locale}
    defaults: { _controller: ABCoreBundle:Reservation:reservation }
    requirements:
        _locale: fr|en

ab_core_update_reservation:
    path: /modification_reservation/{id}/{_locale}
    defaults: {_controller: ABCoreBundle:Reservation:updateReservation}
    requirements:
        id: \d+
        _locale: fr|en

ab_core_reservation_seconde_etape:
    path:    /reservation/etape-2/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Reservation:reservationSecondeEtape }
    requirements:
        id: \d+
        _locale: fr|en

ab_core_paiement:
    path:    /paiement/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Order:paiement }
    requirements:
        id: \d+
        _locale: fr|en

ab_core_stripe:
    path:    /stripe/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Order:stripe }
    requirements:
        id: \d+
        _locale: fr|en

ab_core_partage:
    path:    /partage/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Order:partage }
    requirements:
         _locale: fr|en

ab_core_partagePaypal:
    path:    /partagePaypal
    defaults: { _controller: ABCoreBundle:Order:partagePaypal}

EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode

ab_core_pdfbis:
    path:    /pdf/create/{id}
    defaults: {_controller: ABCoreBundle:Order:CreatePdf}
    requirements:
            id: \d+
