ab_core_accueil:
    path:     /{_locale}
    defaults: { _controller: ABCoreBundle:Core:index, _locale: fr }
    requirements:
        _locale: fr|en

ab_core_reservation:
    path:    /reservation/{_locale}
    defaults: { _controller: ABCoreBundle:Reservation:reservation }
    requirements:
        _locale: fr|en

ab_core_update_reservation:
    path: /modification_reservation/{id}/{_locale}
    defaults: {_controller: ABCoreBundle:Reservation:updateReservation}
    requirements:
        id: \d+
        _locale: fr|en

ab_core_reservation_seconde_etape:
    path:    /reservation/etape-2/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Reservation:reservationSecondeEtape }
    requirements:
        id: \d+
        _locale: fr|en

ab_core_paiement:
    path:    /paiement/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Order:paiement }
    requirements:
        id: \d+
        _locale: fr|en


ab_core_stripe:
    path:    /paiement/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Order:stripe }
    requirements:
        id: \d+
        _locale: fr|en


ab_core_partage:
    path:    /partage/{_locale}
    defaults: { _controller: ABCoreBundle:Core:partage }
    requirements:
         _locale: fr|en

ab_core_error:
    path:    /error/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:Core:error }
    requirements:
         id: \d+
         _locale: fr|en


ab_core_pdf:
    path:    /pdf/{id}/{_locale}
    defaults: { _controller: ABCoreBundle:PDF:generatePdf }
    requirements:
        id: \d+
        _locale: fr|en


my_barcode_playground:
    resource: "@MopaBarcodeBundle/Resources/config/routing/barcode_playground.yml"
    prefix:   /


