<?php

namespace AB\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Validation_commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Validation_commandeRepository extends EntityRepository
{
}
